var annotated =
[
    [ "Ui", null, [
      [ "digiholoMainGui", "class_ui_1_1digiholo_main_gui.html", null ]
    ] ],
    [ "abstract_fringe_analyser", "classabstract__fringe__analyser.html", "classabstract__fringe__analyser" ],
    [ "abstract_smart_tile_unwrapper", "classabstract__smart__tile__unwrapper.html", "classabstract__smart__tile__unwrapper" ],
    [ "abstract_smart_unwrapper", "classabstract__smart__unwrapper.html", "classabstract__smart__unwrapper" ],
    [ "abstract_tile_merger", "classabstract__tile__merger.html", "classabstract__tile__merger" ],
    [ "abstract_tile_unwrapper", "classabstract__tile__unwrapper.html", "classabstract__tile__unwrapper" ],
    [ "abstract_unwrapper", "classabstract__unwrapper.html", "classabstract__unwrapper" ],
    [ "col_major_float_image", "classcol__major__float__image.html", "classcol__major__float__image" ],
    [ "digiholoMainGui", "classdigiholo_main_gui.html", "classdigiholo_main_gui" ],
    [ "EDGE", "struct_e_d_g_e.html", "struct_e_d_g_e" ],
    [ "float_image", "classfloat__image.html", "classfloat__image" ],
    [ "grad_fit_tile_unwrapper", "classgrad__fit__tile__unwrapper.html", "classgrad__fit__tile__unwrapper" ],
    [ "minimization_tile_unwrapper", "classminimization__tile__unwrapper.html", "classminimization__tile__unwrapper" ],
    [ "PIXEL", "struct_p_i_x_e_l.html", "struct_p_i_x_e_l" ],
    [ "qt_meta_stringdata_digiholoMainGui_t", "structqt__meta__stringdata__digiholo_main_gui__t.html", "structqt__meta__stringdata__digiholo_main_gui__t" ],
    [ "qt_meta_stringdata_ReconstructionThread_t", "structqt__meta__stringdata___reconstruction_thread__t.html", "structqt__meta__stringdata___reconstruction_thread__t" ],
    [ "ReconstructionThread", "class_reconstruction_thread.html", "class_reconstruction_thread" ],
    [ "row_major_float_image", "classrow__major__float__image.html", "classrow__major__float__image" ],
    [ "simple1d_tile_merger", "classsimple1d__tile__merger.html", "classsimple1d__tile__merger" ],
    [ "smart_tile", "classsmart__tile.html", "classsmart__tile" ],
    [ "smart_tile_junction", "classsmart__tile__junction.html", "classsmart__tile__junction" ],
    [ "smart_tiled_image", "classsmart__tiled__image.html", "classsmart__tiled__image" ],
    [ "smart_tilegroup", "classsmart__tilegroup.html", "classsmart__tilegroup" ],
    [ "srncp_tile_merger", "classsrncp__tile__merger.html", "classsrncp__tile__merger" ],
    [ "srncp_unwrapper", "classsrncp__unwrapper.html", "classsrncp__unwrapper" ],
    [ "Strand_tile_unwrapper", "class_strand__tile__unwrapper.html", "class_strand__tile__unwrapper" ],
    [ "Takeda_FFTW_fringe_analyser", "class_takeda___f_f_t_w__fringe__analyser.html", "class_takeda___f_f_t_w__fringe__analyser" ],
    [ "tesselated_image", "classtesselated__image.html", "classtesselated__image" ],
    [ "tile", "classtile.html", "classtile" ],
    [ "tile_image", "classtile__image.html", null ],
    [ "tile_junction", "classtile__junction.html", "classtile__junction" ],
    [ "tile_merge_unwrapper", "classtile__merge__unwrapper.html", "classtile__merge__unwrapper" ],
    [ "tilegroup", "classtilegroup.html", "classtilegroup" ],
    [ "Ui_digiholoMainGui", "class_ui__digiholo_main_gui.html", "class_ui__digiholo_main_gui" ]
];